### ISSUE TITLE
how to get the ETH-USD price?

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-oracle#2]
It's not obvious to me how to do this. Is it straightforward? Or are there technical obstacles or missing pieces?

I hope to spend some time figuring this out, but in case someone else knows off hand, I'm sharing the question here.

**Comment by michaelfig** [comment]
> It's not obvious to me how to do this. Is it straightforward? Or are there technical obstacles or missing pieces?

We are still working on the contract layers that would make this straightforward.  Feel free to ask on Discord.

**Comment by dckc** [comment]
Thanks.

Meanwhile... I wrote USD/ETH thinking the notation would be "USD per ETH" but the convention is evidently the other way: https://feeds.chain.link/eth-usd

**Comment by erights** [comment]
Damn! If they wanted to put the denominator first, they should have used a backslash.

**Comment by michaelfig** [comment]
> Damn! If they wanted to put the denominator first, they should have used a backslash.

It's not so bad.  The convention is `eth-usd` which is read as "ETH to USD" and doesn't need a slash at all.
