### ISSUE TITLE
OracleHandler is leaked via E(zoe).getTerms(contractInstance)

### ISSUE THREAD

**Issue by zarutian** [Agoric/dapp-oracle#3]
I take that the contract instance gotten from start(zcf) in  ./contract/src/contract.js is meant to be a "toll-proxy" for Oracle handler, no?

Because `E(E.G(E(zoe).getTerms(), "oracleHandler"))).onQuery(query, feePaid)` by-passes the contract all together.

**Comment by zarutian** [comment]
@michaelfig there is an easy fix though.

**Comment by michaelfig** [comment]
> @michaelfig there is an easy fix though.

Installing the handler via the `creatorFacet`?  If that's what you have in mind, or another solution, I'd really appreciate a PR.

**Comment by zarutian** [comment]
here is one PR #4

**Comment by zarutian** [comment]
fixed in pull-request #6
